	--- 5 --- Magnitude Analysis
-- Compare the measure values by categories.
-- It helps us understand the importance of different categories.

-- Find the total customers by country 
select 
country,
count(*) as Total_Customers
from gold.dim_customers
group by country
order by Total_Customers desc

-- Find total customers by gender 
select 
sum(case when gender = 'Male' then 1 else 0 end ) as Total_Male_Customers,
sum(case when gender = 'Female' then 1 else 0 end ) as Total_Female_Customers,
sum(case when gender = 'n/a' then 1 else 0 end ) as Total_Customers_without_gender
from gold.dim_customers

select 
gender,
count(*) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- Find total products by category	
select 
category,
count(product_key) as Total_Products
from gold.dim_products
group by category
order by  Total_Products desc

-- What is the average costs in each category?
select 
	category,
	avg(cost) as Average_Cost
from gold.dim_products
group by category
order by Average_Cost desc

-- What is the total revenue generated for each category?
select 
	p.category ,
	sum (f.sales_amount) as Total_Revenue
from gold.fact_sales f
left join gold.dim_products p on p.product_key = f.product_key
group by p.category

-- Find the total revenue generated by each customer
select 
	c.first_name + ' ' + c.last_name as Customer_Name,
	c.customer_key,
	sum (f.sales_amount) as Total_Revenue
from gold.fact_sales f
left join gold.dim_customers c on c.customer_key = f.customer_key
group by c.customer_key, c.first_name, c.last_name
order by total_revenue desc

-- what is the distribution of sold items accross countries

select 
	c.country,
	count(p.product_name) as Total_Products
from gold.fact_sales f
left join gold.dim_customers c on f.customer_key = c.customer_key
left join gold.dim_products p on p.product_key = f.product_key
group by c.country
order by Total_Products desc
